### ISSUE TITLE
Depup failed due to permission denied

### ISSUE THREAD

**Issue by maruloop** [maruloop/action-regal#5]
https://github.com/reviewdog/action-regal/actions/runs/9626175482

@haya14busa When you have time, could you check the settings of this repository?
The permission in the workflow should be correct.
https://github.com/reviewdog/action-regal/blob/main/.github/workflows/depup.yml#L14

**Comment by haya14busa** [comment]
![image](https://github.com/reviewdog/action-regal/assets/3797062/d2bd42d4-974f-4ba9-8b9c-242960796094)

Thank you for letting me know. 
It looks like the default permission changed? I fixed the permission and changed your role to admin of this repo.

**Comment by haya14busa** [comment]
The depup workflow succeeded. https://github.com/reviewdog/action-regal/pull/6

Thanks!
